server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/paper_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true


logging:
  level:
    com.shi: debug

